Updater: Fix crash when attempting to delete update
05-16 07:38:38.607  6370  6370 E AndroidRuntime: Caused by:
java.lang.NullPointerException: Attempt to read from field
'org.lineageos.updater.data.UpdateStatus org.lineageos.updater.data.Update.status'
on a null object reference in method 'void org.lineageos.updater.controller
.UpdaterService$1.onReceive(android.content.Context, android.content.Intent)'

Ideally, an update that is pending reboot should not be removable.

Change-Id: I41e48eda625797ea1db4c3e896a9ce883f44ef70